version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  server:
    build: ./server
    container_name: nodejs-server
    ports:
      - "3000:3000"
    volumes:
      - ./server:/usr/src/app
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/url-shortener

volumes:
  mongo-data:
